# Generated by Django 3.2.7 on 2021-09-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210913_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='SK Blogs', max_length=255),
        ),
    ]
