# Generated by Django 3.2.7 on 2021-09-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210915_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click here to read more...', max_length=255),
            preserve_default=False,
        ),
    ]
