# Generated by Django 3.2.7 on 2021-09-19 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='namr',
            new_name='name',
        ),
    ]
